# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='audio/podcast')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('number', models.PositiveIntegerField(default=1, help_text='The episode number')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of the episode')),
                ('show_notes', models.TextField(help_text='Show notes here!')),
            ],
        ),
    ]
